module.exports = {
  theme: {
    // If you want to override default tailwind values with your own set of values, then put them here

    extend: {
      // Here you can extend values generated by default.
      colors: {
        "starwatch-orange": "#F59621",
        "starwatch-hover": "#FD954F",
      },
    },
  },
  variants: {},
  plugins: [],
}
